@baseUrl = http://127.0.0.1:8000

GET {{baseUrl}}

###

#Регистрация
POST {{baseUrl}}/user/
Content-Type: application/json

{
    "username":"username",
    "password":"password",
    "email":"test@email.com"
}

###

#Получить токен
POST {{baseUrl}}/api/token/
Content-Type: application/json

{
    "email":"test@email.com",
    "password":"password"
}